### ISSUE TITLE
TypeError: Cannot read property 'scripts' of undefined

### ISSUE THREAD

**Issue by maksimkurb** [slawo/chrome-dev-webpack-plugin#1]
You should handle situation when plugin don't have `background.scripts` or `content_scripts.js` keys in `manifest.js`

```
chrome-dev-webpack-plugin - error: TypeError: Cannot read property 'scripts' of undefined
  at manifestSync.sync.then (.../node_modules/chrome-dev-webpack-plugin/lib/chrome-dev-webpack-plugin.js:136:34)
  ...
```

**Comment by slawo** [comment]
@maksimkurb  Hi. This is not a situation I had to deal with so far... I will look into it.

**Comment by cawa-93** [comment]
Yeap. This is my `manifest.json`
```json
{
  "chrome_settings_overrides" : {
    "homepage": "index.html"
  },
  "chrome_url_overrides" : {
    "newtab": "index.html"
  },
  "permissions": [
    "history",
    "webRequest",
    "sessions",
    "storage",
    "topSites"
  ]
}
```
I use webpack and vue for build and get follow error:
```
chrome-dev-webpack-plugin - error: TypeError: Cannot read property 'scripts' of undefined
    at manifestSync.sync.then (D:\Develop\ff-start-page\ff-start\node_modules\chrome-dev-webpack-plugin\lib\chrome-dev-webpack-plugin.js:136:34)
    at tryCatcher (D:\Develop\ff-start-page\ff-start\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (D:\Develop\ff-start-page\ff-start\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (D:\Develop\ff-start-page\ff-start\node_modules\bluebird\js\main\promise.js:584:18)
    at Async._drainQueue (D:\Develop\ff-start-page\ff-start\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (D:\Develop\ff-start-page\ff-start\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (D:\Develop\ff-start-page\ff-start\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
